import type { Metadata } from "next";
import { M_PLUS_1p } from "next/font/google";
import "./globals.css";

const mPlus1p = M_PLUS_1p({
  weight: ["100", "300", "400", "500", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-m-plus-1p",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${mPlus1p.variable} antialiased flex justify-center`}>
        <div className="w-full h-full max-w-[500px] max-h-[100vh] relative">
          {children}
        </div>
      </body>
    </html>
  );
}
